apiVersion: v1
kind: Template
metadata:
  name: reports-template-simple
  annotations:
    openshift.io/display-name: Plantilla (Reports) servicio Simple
    iconClass: fa fa-code
    description: Plantilla para generar servicios FIS Simple
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${PARAM_IMAGE_NAME}
- apiVersion: v1
  kind: BuildConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
      provider: fabric8
      group: ar.com.lasegunda
    name: ${PARAM_APP_NAME}
  spec:
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    runPolicy: Serial
    source:
      type: Binary
    strategy:
      sourceStrategy:
        from:
          kind: ImageStreamTag
          name: fis-java-openshift:2.0
          namespace: openshift
    output:
      to:
        kind: ImageStreamTag
        name: ${PARAM_IMAGE_NAME}:latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    template:
      metadata:
        annotations:
           prometheus.io/path: /metrics
           prometheus.io/port: "9779"
           prometheus.io/scrape: "true"   
        labels:
          deploymentConfig: ${PARAM_APP_NAME}
          name: ${PARAM_APP_NAME}
      spec:
        containers:
          - name: ${PARAM_APP_NAME}
            image: ${PARAM_IMAGE_NAME}:latest
            volumeMounts:
            - name: config-volume
              mountPath: /deployments/application.properties
              subPath: application.properties
            - name: certs-jks
              mountPath: /etc/secret/all-clusters.jks
              subPath: all-clusters.jks
            env:
              - name: TZ
                value: America/Argentina/Buenos_Aires
              - name: JAVA_OPTIONS
                value: -Djavax.net.ssl.trustStore=/etc/secret/all-clusters.jks -Djavax.net.ssl.trustStoreType=JKS
              - name: JAVAX_NET_SSL_TRUSTSTOREPASSWORD
                valueFrom:
                  secretKeyRef:
                    key: certjkspass
                    name: cert-jks-pass
        volumes:
        - name: config-volume
          configMap:
            name: reports
        - name: certs-jks
          secret:
            defaultMode: 420
            secretName: cert-jks
            image: ${PARAM_IMAGE_NAME}:latest
            ports:
              - containerPort: 8080
                protocol: TCP
              - containerPort: 8082
                protocol: TCP
              - containerPort: 9779
                protocol: TCP
            readinessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 20
            livenessProbe:
              failureThreshold: 3
              httpGet:
                path: /health
                port: 8080
                scheme: HTTP
              initialDelaySeconds: 120
              periodSeconds: 10
              successThreshold: 1
              timeoutSeconds: 20
            resources:
              limits:
                cpu: 500m
                memory: 300Mi
              requests:
                cpu: 50m
                memory: 100Mi
    triggers: []
    replicas: 1
    strategy:
      type: Rolling
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${PARAM_APP_NAME}-health
    name: ${PARAM_APP_NAME}-health
  spec:
    ports:
      - port: 8082
        protocol: TCP
        targetPort: 8082
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${PARAM_APP_NAME}-prometheus
    name: ${PARAM_APP_NAME}-prometheus
  spec:
    ports:
      - port: 9779
        protocol: TCP
        targetPort: 9779
    selector:
      deploymentConfig: ${PARAM_APP_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Route
  metadata:
    labels:
      app: ${PARAM_APP_NAME}
    name: ${PARAM_APP_NAME}
  spec:
    to:
      kind: Service
      name: ${PARAM_APP_NAME}
      weight: 100
    tls:
      termination: edge
    wildcardPolicy: None
parameters:
- description: The application name
  displayName: Application name
  name: PARAM_APP_NAME
  value: ${PARAM_APP_NAME}
  required: true
- description: The image name
  displayName: Image name
  name: PARAM_IMAGE_NAME
  value: ${PARAM_APP_NAME}
  required: true
